### ISSUE TITLE
turing_machine example prints nothing

### ISSUE THREAD

**Issue by genmeblog** [m1cha1s/sorth#2]
When I run ` cargo run --example file_exec turing_machine` nothing is printed

```
$ cargo run --example file_exec turing_machine
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/file_exec turing_machine`
$
```

**Comment by m1cha1s** [comment]
If you want to run the turing machine example that is currently under development you have to run this:
```
$ cargo run --example file_exec turing
```

**Comment by m1cha1s** [comment]
This has been pointed out in the updated README in version v0.2.1.
